// script.js
// Ejemplo de datos: reemplazalos por tus textos reales.
// Estructura: categories: [{ id, title, meta, items: [{title, quote, ref, link, book, type, source}] }]

const data = [
  {
    id: "cat-1",
    title: "Scientific Absurdities & Historical Inaccuracies",
    meta: "Ejemplos de pasajes con problemas técnicos/históricos",
    items: [
      {
        title: "Creation account mismatch",
        quote: "Versión A y versión B parecen contar la creación de forma diferente.",
        ref: "Genesis 1:1 / Genesis 2:4",
        link: "#",
        book: "Genesis",
        type: "Inaccuracy",
        source: "Skeptics Annotated"
      },
      {
        title: "Ages of the patriarchs",
        quote: "Ciertas edades reportadas parecen incompatibles entre capítulos.",
        ref: "Genesis 5",
        link: "#",
        book: "Genesis",
        type: "Scientific Absurdity",
        source: "Skeptics Annotated"
      }
    ]
  },
  {
    id: "cat-2",
    title: "Cruelty & Violence",
    meta: "Pasajes que mandan violencia o castigos severos",
    items: [
      {
        title: "Punishments prescribed",
        quote: "Mandatos de castigo corporal severo en ciertos textos.",
        ref: "Deuteronomy X",
        link: "#",
        book: "Deuteronomy",
        type: "Moral",
        source: "Author notes"
      }
    ]
  },
  {
    id: "cat-3",
    title: "Misogyny & Discrimination",
    meta: "Pasajes con lenguaje o leyes discriminatorias",
    items: [
      {
        title: "Laws about women",
        quote: "Leyes antiguas que regulan fuertemente a mujeres.",
        ref: "Leviticus Y",
        link: "#",
        book: "Leviticus",
        type: "Social",
        source: "Skeptics Annotated"
      }
    ]
  }
];

// ---- render & controls ----
const filters = {
  book: "All",
  type: "All",
  source: "All",
  search: ""
};

function uniqueValuesFromData(key){
  const set = new Set();
  data.forEach(cat => cat.items.forEach(it => set.add(it[key] || 'Unknown')));
  return Array.from(set).sort();
}

function populateFilterOptions(){
  const bookSel = document.getElementById('filter-book');
  const typeSel = document.getElementById('filter-type');
  const sourceSel = document.getElementById('filter-source');

  uniqueValuesFromData('book').forEach(b=>{
    const o = document.createElement('option'); o.value = b; o.textContent = b; bookSel.appendChild(o);
  });
  uniqueValuesFromData('type').forEach(b=>{
    const o = document.createElement('option'); o.value = b; o.textContent = b; typeSel.appendChild(o);
  });
  uniqueValuesFromData('source').forEach(b=>{
    const o = document.createElement('option'); o.value = b; o.textContent = b; sourceSel.appendChild(o);
  });

  bookSel.addEventListener('change', e=>{ filters.book = e.target.value; render(); });
  typeSel.addEventListener('change', e=>{ filters.type = e.target.value; render(); });
  sourceSel.addEventListener('change', e=>{ filters.source = e.target.value; render(); });

  document.getElementById('search').addEventListener('input', e=>{
    filters.search = e.target.value.trim().toLowerCase();
    render();
  });
}

function matchesFilter(item){
  if(filters.book !== 'All' && item.book !== filters.book) return false;
  if(filters.type !== 'All' && item.type !== filters.type) return false;
  if(filters.source !== 'All' && item.source !== filters.source) return false;
  if(filters.search){
    const hay = (item.quote + ' ' + item.title + ' ' + item.ref).toLowerCase();
    if(!hay.includes(filters.search)) return false;
  }
  return true;
}

function render(){
  const content = document.getElementById('content');
  content.innerHTML = '';

  // cuando no hay resultados, mostrar mensaje
  let totalMatches = 0;

  data.forEach(cat=>{
    const filteredItems = cat.items.filter(matchesFilter);
    if(filteredItems.length === 0) return;

    totalMatches += filteredItems.length;

    const catEl = document.createElement('article');
    catEl.className = 'category';
    catEl.id = cat.id;

    const h2 = document.createElement('h2'); h2.textContent = cat.title;
    const meta = document.createElement('div'); meta.className = 'meta'; meta.textContent = cat.meta;

    const list = document.createElement('div');
    filteredItems.forEach(it=>{
      const itemEl = document.createElement('div'); itemEl.className = 'item';
      const quote = document.createElement('div'); quote.className = 'quote';
      const bq = document.createElement('blockquote'); bq.textContent = it.quote;
      const ref = document.createElement('div'); ref.className = 'ref';
      ref.innerHTML = `<strong>${it.title}</strong> — ${it.ref} • <a href="${it.link}" target="_blank" rel="noopener">ver</a>`;

      quote.appendChild(bq);
      quote.appendChild(ref);
      itemEl.appendChild(quote);
      list.appendChild(itemEl);
    });

    // small numbered list of items at bottom (contradictions list style)
    const smallList = document.createElement('div'); smallList.className = 'contradictions-list';
    const ol = document.createElement('ol');
    filteredItems.forEach(it=>{
      const li = document.createElement('li');
      li.innerHTML = `<a href="${it.link}" target="_blank" rel="noopener">${it.title} — ${it.ref}</a>`;
      ol.appendChild(li);
    });
    smallList.appendChild(ol);

    catEl.appendChild(h2);
    catEl.appendChild(meta);
    catEl.appendChild(list);
    catEl.appendChild(smallList);

    content.appendChild(catEl);
  });

  if(totalMatches === 0){
    const no = document.createElement('div'); no.style.padding = '18px'; no.textContent = 'No se encontraron resultados con esos filtros.';
    content.appendChild(no);
  }
}

function expandAll(){
  document.querySelectorAll('.category').forEach(cat=>{
    cat.style.boxShadow = '0 12px 30px rgba(20,30,50,0.06)';
    cat.querySelectorAll('.item blockquote').forEach(bq=> bq.style.maxHeight = 'none');
  });
}
function collapseAll(){
  document.querySelectorAll('.category').forEach(cat=>{
    cat.style.boxShadow = '';
    cat.querySelectorAll('.item blockquote').forEach(bq=> bq.style.maxHeight = '');
  });
}

// init
populateFilterOptions();
render();

// ----- Arc Diagram / Ref Map -----
function drawViz() {
  const vizEl = document.getElementById("viz");
  const width = vizEl.clientWidth || 800;
  const height = vizEl.clientHeight || 500;

  // margen perimetral
  const margin = {top: 460, right: 40, bottom: 40, left: -70};
  const innerWidth = width - margin.left - margin.right;
  const innerHeight = height - margin.top - margin.bottom;

  // datos de ejemplo
  const nodes = [
{id: "Génesis 1"},
{id: "Génesis 2"},
{id: "Génesis 3"},
{id: "Génesis 4"},
{id: "Génesis 5"},
{id: "Génesis 6"},
{id: "Génesis 7"},
{id: "Génesis 8"},
{id: "Génesis 9"},
{id: "Génesis 10"},
{id: "Génesis 11"},
{id: "Génesis 12"},
{id: "Génesis 13"},
{id: "Génesis 14"},
{id: "Génesis 15"},
{id: "Génesis 16"},
{id: "Génesis 17"},
{id: "Génesis 18"},
{id: "Génesis 19"},
{id: "Génesis 20"},
{id: "Génesis 21"},
{id: "Génesis 22"},
{id: "Génesis 23"},
{id: "Génesis 24"},
{id: "Génesis 25"},
{id: "Génesis 26"},
{id: "Génesis 27"},
{id: "Génesis 28"},
{id: "Génesis 29"},
{id: "Génesis 30"},
{id: "Génesis 31"},
{id: "Génesis 32"},
{id: "Génesis 33"},
{id: "Génesis 34"},
{id: "Génesis 35"},
{id: "Génesis 36"},
{id: "Génesis 37"},
{id: "Génesis 38"},
{id: "Génesis 39"},
{id: "Génesis 40"},
{id: "Génesis 41"},
{id: "Génesis 42"},
{id: "Génesis 43"},
{id: "Génesis 44"},
{id: "Génesis 45"},
{id: "Génesis 46"},
{id: "Génesis 47"},
{id: "Génesis 48"},
{id: "Génesis 49"},
{id: "Génesis 50"},
{id: "Éxodo 1"},
{id: "Éxodo 2"},
{id: "Éxodo 3"},
{id: "Éxodo 4"},
{id: "Éxodo 5"},
{id: "Éxodo 6"},
{id: "Éxodo 7"},
{id: "Éxodo 8"},
{id: "Éxodo 9"},
{id: "Éxodo 10"},
{id: "Éxodo 11"},
{id: "Éxodo 12"},
{id: "Éxodo 13"},
{id: "Éxodo 14"},
{id: "Éxodo 15"},
{id: "Éxodo 16"},
{id: "Éxodo 17"},
{id: "Éxodo 18"},
{id: "Éxodo 19"},
{id: "Éxodo 20"},
{id: "Éxodo 21"},
{id: "Éxodo 22"},
{id: "Éxodo 23"},
{id: "Éxodo 24"},
{id: "Éxodo 25"},
{id: "Éxodo 26"},
{id: "Éxodo 27"},
{id: "Éxodo 28"},
{id: "Éxodo 29"},
{id: "Éxodo 30"},
{id: "Éxodo 31"},
{id: "Éxodo 32"},
{id: "Éxodo 33"},
{id: "Éxodo 34"},
{id: "Éxodo 35"},
{id: "Éxodo 36"},
{id: "Éxodo 37"},
{id: "Éxodo 38"},
{id: "Éxodo 39"},
{id: "Éxodo 40"},
{id: "Levítico 1"},
{id: "Levítico 2"},
{id: "Levítico 3"},
{id: "Levítico 4"},
{id: "Levítico 5"},
{id: "Levítico 6"},
{id: "Levítico 7"},
{id: "Levítico 8"},
{id: "Levítico 9"},
{id: "Levítico 10"},
{id: "Levítico 11"},
{id: "Levítico 12"},
{id: "Levítico 13"},
{id: "Levítico 14"},
{id: "Levítico 15"},
{id: "Levítico 16"},
{id: "Levítico 17"},
{id: "Levítico 18"},
{id: "Levítico 19"},
{id: "Levítico 20"},
{id: "Levítico 21"},
{id: "Levítico 22"},
{id: "Levítico 23"},
{id: "Levítico 24"},
{id: "Levítico 25"},
{id: "Levítico 26"},
{id: "Levítico 27"},
{id: "Números 1"},
{id: "Números 2"},
{id: "Números 3"},
{id: "Números 4"},
{id: "Números 5"},
{id: "Números 6"},
{id: "Números 7"},
{id: "Números 8"},
{id: "Números 9"},
{id: "Números 10"},
{id: "Números 11"},
{id: "Números 12"},
{id: "Números 13"},
{id: "Números 14"},
{id: "Números 15"},
{id: "Números 16"},
{id: "Números 17"},
{id: "Números 18"},
{id: "Números 19"},
{id: "Números 20"},
{id: "Números 21"},
{id: "Números 22"},
{id: "Números 23"},
{id: "Números 24"},
{id: "Números 25"},
{id: "Números 26"},
{id: "Números 27"},
{id: "Números 28"},
{id: "Números 29"},
{id: "Números 30"},
{id: "Números 31"},
{id: "Números 32"},
{id: "Números 33"},
{id: "Números 34"},
{id: "Números 35"},
{id: "Números 36"},
{id: "Deuteronomio 1"},
{id: "Deuteronomio 2"},
{id: "Deuteronomio 3"},
{id: "Deuteronomio 4"},
{id: "Deuteronomio 5"},
{id: "Deuteronomio 6"},
{id: "Deuteronomio 7"},
{id: "Deuteronomio 8"},
{id: "Deuteronomio 9"},
{id: "Deuteronomio 10"},
{id: "Deuteronomio 11"},
{id: "Deuteronomio 12"},
{id: "Deuteronomio 13"},
{id: "Deuteronomio 14"},
{id: "Deuteronomio 15"},
{id: "Deuteronomio 16"},
{id: "Deuteronomio 17"},
{id: "Deuteronomio 18"},
{id: "Deuteronomio 19"},
{id: "Deuteronomio 20"},
{id: "Deuteronomio 21"},
{id: "Deuteronomio 22"},
{id: "Deuteronomio 23"},
{id: "Deuteronomio 24"},
{id: "Deuteronomio 25"},
{id: "Deuteronomio 26"},
{id: "Deuteronomio 27"},
{id: "Deuteronomio 28"},
{id: "Deuteronomio 29"},
{id: "Deuteronomio 30"},
{id: "Deuteronomio 31"},
{id: "Deuteronomio 32"},
{id: "Deuteronomio 33"},
{id: "Deuteronomio 34"},
{id: "Josué 1"},
{id: "Josué 2"},
{id: "Josué 3"},
{id: "Josué 4"},
{id: "Josué 5"},
{id: "Josué 6"},
{id: "Josué 7"},
{id: "Josué 8"},
{id: "Josué 9"},
{id: "Josué 10"},
{id: "Josué 11"},
{id: "Josué 12"},
{id: "Josué 13"},
{id: "Josué 14"},
{id: "Josué 15"},
{id: "Josué 16"},
{id: "Josué 17"},
{id: "Josué 18"},
{id: "Josué 19"},
{id: "Josué 20"},
{id: "Josué 21"},
{id: "Josué 22"},
{id: "Josué 23"},
{id: "Josué 24"},
{id: "Jueces 1"},
{id: "Jueces 2"},
{id: "Jueces 3"},
{id: "Jueces 4"},
{id: "Jueces 5"},
{id: "Jueces 6"},
{id: "Jueces 7"},
{id: "Jueces 8"},
{id: "Jueces 9"},
{id: "Jueces 10"},
{id: "Jueces 11"},
{id: "Jueces 12"},
{id: "Jueces 13"},
{id: "Jueces 14"},
{id: "Jueces 15"},
{id: "Jueces 16"},
{id: "Jueces 17"},
{id: "Jueces 18"},
{id: "Jueces 19"},
{id: "Jueces 20"},
{id: "Jueces 21"},
{id: "Rut 1"},
{id: "Rut 2"},
{id: "Rut 3"},
{id: "Rut 4"},
{id: "1 Samuel 1"},
{id: "1 Samuel 2"},
{id: "1 Samuel 3"},
{id: "1 Samuel 4"},
{id: "1 Samuel 5"},
{id: "1 Samuel 6"},
{id: "1 Samuel 7"},
{id: "1 Samuel 8"},
{id: "1 Samuel 9"},
{id: "1 Samuel 10"},
{id: "1 Samuel 11"},
{id: "1 Samuel 12"},
{id: "1 Samuel 13"},
{id: "1 Samuel 14"},
{id: "1 Samuel 15"},
{id: "1 Samuel 16"},
{id: "1 Samuel 17"},
{id: "1 Samuel 18"},
{id: "1 Samuel 19"},
{id: "1 Samuel 20"},
{id: "1 Samuel 21"},
{id: "1 Samuel 22"},
{id: "1 Samuel 23"},
{id: "1 Samuel 24"},
{id: "1 Samuel 25"},
{id: "1 Samuel 26"},
{id: "1 Samuel 27"},
{id: "1 Samuel 28"},
{id: "1 Samuel 29"},
{id: "1 Samuel 30"},
{id: "1 Samuel 31"},
{id: "2 Samuel 1"},
{id: "2 Samuel 2"},
{id: "2 Samuel 3"},
{id: "2 Samuel 4"},
{id: "2 Samuel 5"},
{id: "2 Samuel 6"},
{id: "2 Samuel 7"},
{id: "2 Samuel 8"},
{id: "2 Samuel 9"},
{id: "2 Samuel 10"},
{id: "2 Samuel 11"},
{id: "2 Samuel 12"},
{id: "2 Samuel 13"},
{id: "2 Samuel 14"},
{id: "2 Samuel 15"},
{id: "2 Samuel 16"},
{id: "2 Samuel 17"},
{id: "2 Samuel 18"},
{id: "2 Samuel 19"},
{id: "2 Samuel 20"},
{id: "2 Samuel 21"},
{id: "2 Samuel 22"},
{id: "2 Samuel 23"},
{id: "2 Samuel 24"},
{id: "1 Reyes 1"},
{id: "1 Reyes 2"},
{id: "1 Reyes 3"},
{id: "1 Reyes 4"},
{id: "1 Reyes 5"},
{id: "1 Reyes 6"},
{id: "1 Reyes 7"},
{id: "1 Reyes 8"},
{id: "1 Reyes 9"},
{id: "1 Reyes 10"},
{id: "1 Reyes 11"},
{id: "1 Reyes 12"},
{id: "1 Reyes 13"},
{id: "1 Reyes 14"},
{id: "1 Reyes 15"},
{id: "1 Reyes 16"},
{id: "1 Reyes 17"},
{id: "1 Reyes 18"},
{id: "1 Reyes 19"},
{id: "1 Reyes 20"},
{id: "1 Reyes 21"},
{id: "1 Reyes 22"},
{id: "2 Reyes 1"},
{id: "2 Reyes 2"},
{id: "2 Reyes 3"},
{id: "2 Reyes 4"},
{id: "2 Reyes 5"},
{id: "2 Reyes 6"},
{id: "2 Reyes 7"},
{id: "2 Reyes 8"},
{id: "2 Reyes 9"},
{id: "2 Reyes 10"},
{id: "2 Reyes 11"},
{id: "2 Reyes 12"},
{id: "2 Reyes 13"},
{id: "2 Reyes 14"},
{id: "2 Reyes 15"},
{id: "2 Reyes 16"},
{id: "2 Reyes 17"},
{id: "2 Reyes 18"},
{id: "2 Reyes 19"},
{id: "2 Reyes 20"},
{id: "2 Reyes 21"},
{id: "2 Reyes 22"},
{id: "2 Reyes 23"},
{id: "2 Reyes 24"},
{id: "2 Reyes 25"},
{id: "1 Crónicas 1"},
{id: "1 Crónicas 2"},
{id: "1 Crónicas 3"},
{id: "1 Crónicas 4"},
{id: "1 Crónicas 5"},
{id: "1 Crónicas 6"},
{id: "1 Crónicas 7"},
{id: "1 Crónicas 8"},
{id: "1 Crónicas 9"},
{id: "1 Crónicas 10"},
{id: "1 Crónicas 11"},
{id: "1 Crónicas 12"},
{id: "1 Crónicas 13"},
{id: "1 Crónicas 14"},
{id: "1 Crónicas 15"},
{id: "1 Crónicas 16"},
{id: "1 Crónicas 17"},
{id: "1 Crónicas 18"},
{id: "1 Crónicas 19"},
{id: "1 Crónicas 20"},
{id: "1 Crónicas 21"},
{id: "1 Crónicas 22"},
{id: "1 Crónicas 23"},
{id: "1 Crónicas 24"},
{id: "1 Crónicas 25"},
{id: "1 Crónicas 26"},
{id: "1 Crónicas 27"},
{id: "1 Crónicas 28"},
{id: "1 Crónicas 29"},
{id: "2 Crónicas 1"},
{id: "2 Crónicas 2"},
{id: "2 Crónicas 3"},
{id: "2 Crónicas 4"},
{id: "2 Crónicas 5"},
{id: "2 Crónicas 6"},
{id: "2 Crónicas 7"},
{id: "2 Crónicas 8"},
{id: "2 Crónicas 9"},
{id: "2 Crónicas 10"},
{id: "2 Crónicas 11"},
{id: "2 Crónicas 12"},
{id: "2 Crónicas 13"},
{id: "2 Crónicas 14"},
{id: "2 Crónicas 15"},
{id: "2 Crónicas 16"},
{id: "2 Crónicas 17"},
{id: "2 Crónicas 18"},
{id: "2 Crónicas 19"},
{id: "2 Crónicas 20"},
{id: "2 Crónicas 21"},
{id: "2 Crónicas 22"},
{id: "2 Crónicas 23"},
{id: "2 Crónicas 24"},
{id: "2 Crónicas 25"},
{id: "2 Crónicas 26"},
{id: "2 Crónicas 27"},
{id: "2 Crónicas 28"},
{id: "2 Crónicas 29"},
{id: "2 Crónicas 30"},
{id: "2 Crónicas 31"},
{id: "2 Crónicas 32"},
{id: "2 Crónicas 33"},
{id: "2 Crónicas 34"},
{id: "2 Crónicas 35"},
{id: "2 Crónicas 36"},
{id: "Esdras 1"},
{id: "Esdras 2"},
{id: "Esdras 3"},
{id: "Esdras 4"},
{id: "Esdras 5"},
{id: "Esdras 6"},
{id: "Esdras 7"},
{id: "Esdras 8"},
{id: "Esdras 9"},
{id: "Esdras 10"},
{id: "Nehemías 1"},
{id: "Nehemías 2"},
{id: "Nehemías 3"},
{id: "Nehemías 4"},
{id: "Nehemías 5"},
{id: "Nehemías 6"},
{id: "Nehemías 7"},
{id: "Nehemías 8"},
{id: "Nehemías 9"},
{id: "Nehemías 10"},
{id: "Nehemías 11"},
{id: "Nehemías 12"},
{id: "Nehemías 13"},
{id: "Ester 1"},
{id: "Ester 2"},
{id: "Ester 3"},
{id: "Ester 4"},
{id: "Ester 5"},
{id: "Ester 6"},
{id: "Ester 7"},
{id: "Ester 8"},
{id: "Ester 9"},
{id: "Ester 10"},
{id: "Job 1"},
{id: "Job 2"},
{id: "Job 3"},
{id: "Job 4"},
{id: "Job 5"},
{id: "Job 6"},
{id: "Job 7"},
{id: "Job 8"},
{id: "Job 9"},
{id: "Job 10"},
{id: "Job 11"},
{id: "Job 12"},
{id: "Job 13"},
{id: "Job 14"},
{id: "Job 15"},
{id: "Job 16"},
{id: "Job 17"},
{id: "Job 18"},
{id: "Job 19"},
{id: "Job 20"},
{id: "Job 21"},
{id: "Job 22"},
{id: "Job 23"},
{id: "Job 24"},
{id: "Job 25"},
{id: "Job 26"},
{id: "Job 27"},
{id: "Job 28"},
{id: "Job 29"},
{id: "Job 30"},
{id: "Job 31"},
{id: "Job 32"},
{id: "Job 33"},
{id: "Job 34"},
{id: "Job 35"},
{id: "Job 36"},
{id: "Job 37"},
{id: "Job 38"},
{id: "Job 39"},
{id: "Job 40"},
{id: "Job 41"},
{id: "Job 42"},
{id: "Salmos 1"},
{id: "Salmos 2"},
{id: "Salmos 3"},
{id: "Salmos 4"},
{id: "Salmos 5"},
{id: "Salmos 6"},
{id: "Salmos 7"},
{id: "Salmos 8"},
{id: "Salmos 9"},
{id: "Salmos 10"},
{id: "Salmos 11"},
{id: "Salmos 12"},
{id: "Salmos 13"},
{id: "Salmos 14"},
{id: "Salmos 15"},
{id: "Salmos 16"},
{id: "Salmos 17"},
{id: "Salmos 18"},
{id: "Salmos 19"},
{id: "Salmos 20"},
{id: "Salmos 21"},
{id: "Salmos 22"},
{id: "Salmos 23"},
{id: "Salmos 24"},
{id: "Salmos 25"},
{id: "Salmos 26"},
{id: "Salmos 27"},
{id: "Salmos 28"},
{id: "Salmos 29"},
{id: "Salmos 30"},
{id: "Salmos 31"},
{id: "Salmos 32"},
{id: "Salmos 33"},
{id: "Salmos 34"},
{id: "Salmos 35"},
{id: "Salmos 36"},
{id: "Salmos 37"},
{id: "Salmos 38"},
{id: "Salmos 39"},
{id: "Salmos 40"},
{id: "Salmos 41"},
{id: "Salmos 42"},
{id: "Salmos 43"},
{id: "Salmos 44"},
{id: "Salmos 45"},
{id: "Salmos 46"},
{id: "Salmos 47"},
{id: "Salmos 48"},
{id: "Salmos 49"},
{id: "Salmos 50"},
{id: "Salmos 51"},
{id: "Salmos 52"},
{id: "Salmos 53"},
{id: "Salmos 54"},
{id: "Salmos 55"},
{id: "Salmos 56"},
{id: "Salmos 57"},
{id: "Salmos 58"},
{id: "Salmos 59"},
{id: "Salmos 60"},
{id: "Salmos 61"},
{id: "Salmos 62"},
{id: "Salmos 63"},
{id: "Salmos 64"},
{id: "Salmos 65"},
{id: "Salmos 66"},
{id: "Salmos 67"},
{id: "Salmos 68"},
{id: "Salmos 69"},
{id: "Salmos 70"},
{id: "Salmos 71"},
{id: "Salmos 72"},
{id: "Salmos 73"},
{id: "Salmos 74"},
{id: "Salmos 75"},
{id: "Salmos 76"},
{id: "Salmos 77"},
{id: "Salmos 78"},
{id: "Salmos 79"},
{id: "Salmos 80"},
{id: "Salmos 81"},
{id: "Salmos 82"},
{id: "Salmos 83"},
{id: "Salmos 84"},
{id: "Salmos 85"},
{id: "Salmos 86"},
{id: "Salmos 87"},
{id: "Salmos 88"},
{id: "Salmos 89"},
{id: "Salmos 90"},
{id: "Salmos 91"},
{id: "Salmos 92"},
{id: "Salmos 93"},
{id: "Salmos 94"},
{id: "Salmos 95"},
{id: "Salmos 96"},
{id: "Salmos 97"},
{id: "Salmos 98"},
{id: "Salmos 99"},
{id: "Salmos 100"},
{id: "Salmos 101"},
{id: "Salmos 102"},
{id: "Salmos 103"},
{id: "Salmos 104"},
{id: "Salmos 105"},
{id: "Salmos 106"},
{id: "Salmos 107"},
{id: "Salmos 108"},
{id: "Salmos 109"},
{id: "Salmos 110"},
{id: "Salmos 111"},
{id: "Salmos 112"},
{id: "Salmos 113"},
{id: "Salmos 114"},
{id: "Salmos 115"},
{id: "Salmos 116"},
{id: "Salmos 117"},
{id: "Salmos 118"},
{id: "Salmos 119"},
{id: "Salmos 120"},
{id: "Salmos 121"},
{id: "Salmos 122"},
{id: "Salmos 123"},
{id: "Salmos 124"},
{id: "Salmos 125"},
{id: "Salmos 126"},
{id: "Salmos 127"},
{id: "Salmos 128"},
{id: "Salmos 129"},
{id: "Salmos 130"},
{id: "Salmos 131"},
{id: "Salmos 132"},
{id: "Salmos 133"},
{id: "Salmos 134"},
{id: "Salmos 135"},
{id: "Salmos 136"},
{id: "Salmos 137"},
{id: "Salmos 138"},
{id: "Salmos 139"},
{id: "Salmos 140"},
{id: "Salmos 141"},
{id: "Salmos 142"},
{id: "Salmos 143"},
{id: "Salmos 144"},
{id: "Salmos 145"},
{id: "Salmos 146"},
{id: "Salmos 147"},
{id: "Salmos 148"},
{id: "Salmos 149"},
{id: "Salmos 150"},
{id: "Proverbios 1"},
{id: "Proverbios 2"},
{id: "Proverbios 3"},
{id: "Proverbios 4"},
{id: "Proverbios 5"},
{id: "Proverbios 6"},
{id: "Proverbios 7"},
{id: "Proverbios 8"},
{id: "Proverbios 9"},
{id: "Proverbios 10"},
{id: "Proverbios 11"},
{id: "Proverbios 12"},
{id: "Proverbios 13"},
{id: "Proverbios 14"},
{id: "Proverbios 15"},
{id: "Proverbios 16"},
{id: "Proverbios 17"},
{id: "Proverbios 18"},
{id: "Proverbios 19"},
{id: "Proverbios 20"},
{id: "Proverbios 21"},
{id: "Proverbios 22"},
{id: "Proverbios 23"},
{id: "Proverbios 24"},
{id: "Proverbios 25"},
{id: "Proverbios 26"},
{id: "Proverbios 27"},
{id: "Proverbios 28"},
{id: "Proverbios 29"},
{id: "Proverbios 30"},
{id: "Proverbios 31"},
{id: "Eclesiastés 1"},
{id: "Eclesiastés 2"},
{id: "Eclesiastés 3"},
{id: "Eclesiastés 4"},
{id: "Eclesiastés 5"},
{id: "Eclesiastés 6"},
{id: "Eclesiastés 7"},
{id: "Eclesiastés 8"},
{id: "Eclesiastés 9"},
{id: "Eclesiastés 10"},
{id: "Eclesiastés 11"},
{id: "Eclesiastés 12"},
{id: "Cantares 1"},
{id: "Cantares 2"},
{id: "Cantares 3"},
{id: "Cantares 4"},
{id: "Cantares 5"},
{id: "Cantares 6"},
{id: "Cantares 7"},
{id: "Cantares 8"},
{id: "Isaías 1"},
{id: "Isaías 2"},
{id: "Isaías 3"},
{id: "Isaías 4"},
{id: "Isaías 5"},
{id: "Isaías 6"},
{id: "Isaías 7"},
{id: "Isaías 8"},
{id: "Isaías 9"},
{id: "Isaías 10"},
{id: "Isaías 11"},
{id: "Isaías 12"},
{id: "Isaías 13"},
{id: "Isaías 14"},
{id: "Isaías 15"},
{id: "Isaías 16"},
{id: "Isaías 17"},
{id: "Isaías 18"},
{id: "Isaías 19"},
{id: "Isaías 20"},
{id: "Isaías 21"},
{id: "Isaías 22"},
{id: "Isaías 23"},
{id: "Isaías 24"},
{id: "Isaías 25"},
{id: "Isaías 26"},
{id: "Isaías 27"},
{id: "Isaías 28"},
{id: "Isaías 29"},
{id: "Isaías 30"},
{id: "Isaías 31"},
{id: "Isaías 32"},
{id: "Isaías 33"},
{id: "Isaías 34"},
{id: "Isaías 35"},
{id: "Isaías 36"},
{id: "Isaías 37"},
{id: "Isaías 38"},
{id: "Isaías 39"},
{id: "Isaías 40"},
{id: "Isaías 41"},
{id: "Isaías 42"},
{id: "Isaías 43"},
{id: "Isaías 44"},
{id: "Isaías 45"},
{id: "Isaías 46"},
{id: "Isaías 47"},
{id: "Isaías 48"},
{id: "Isaías 49"},
{id: "Isaías 50"},
{id: "Isaías 51"},
{id: "Isaías 52"},
{id: "Isaías 53"},
{id: "Isaías 54"},
{id: "Isaías 55"},
{id: "Isaías 56"},
{id: "Isaías 57"},
{id: "Isaías 58"},
{id: "Isaías 59"},
{id: "Isaías 60"},
{id: "Isaías 61"},
{id: "Isaías 62"},
{id: "Isaías 63"},
{id: "Isaías 64"},
{id: "Isaías 65"},
{id: "Isaías 66"},
{id: "Jeremías 1"},
{id: "Jeremías 2"},
{id: "Jeremías 3"},
{id: "Jeremías 4"},
{id: "Jeremías 5"},
{id: "Jeremías 6"},
{id: "Jeremías 7"},
{id: "Jeremías 8"},
{id: "Jeremías 9"},
{id: "Jeremías 10"},
{id: "Jeremías 11"},
{id: "Jeremías 12"},
{id: "Jeremías 13"},
{id: "Jeremías 14"},
{id: "Jeremías 15"},
{id: "Jeremías 16"},
{id: "Jeremías 17"},
{id: "Jeremías 18"},
{id: "Jeremías 19"},
{id: "Jeremías 20"},
{id: "Jeremías 21"},
{id: "Jeremías 22"},
{id: "Jeremías 23"},
{id: "Jeremías 24"},
{id: "Jeremías 25"},
{id: "Jeremías 26"},
{id: "Jeremías 27"},
{id: "Jeremías 28"},
{id: "Jeremías 29"},
{id: "Jeremías 30"},
{id: "Jeremías 31"},
{id: "Jeremías 32"},
{id: "Jeremías 33"},
{id: "Jeremías 34"},
{id: "Jeremías 35"},
{id: "Jeremías 36"},
{id: "Jeremías 37"},
{id: "Jeremías 38"},
{id: "Jeremías 39"},
{id: "Jeremías 40"},
{id: "Jeremías 41"},
{id: "Jeremías 42"},
{id: "Jeremías 43"},
{id: "Jeremías 44"},
{id: "Jeremías 45"},
{id: "Jeremías 46"},
{id: "Jeremías 47"},
{id: "Jeremías 48"},
{id: "Jeremías 49"},
{id: "Jeremías 50"},
{id: "Jeremías 51"},
{id: "Jeremías 52"},
{id: "Lamentaciones 1"},
{id: "Lamentaciones 2"},
{id: "Lamentaciones 3"},
{id: "Lamentaciones 4"},
{id: "Lamentaciones 5"},
{id: "Ezequiel 1"},
{id: "Ezequiel 2"},
{id: "Ezequiel 3"},
{id: "Ezequiel 4"},
{id: "Ezequiel 5"},
{id: "Ezequiel 6"},
{id: "Ezequiel 7"},
{id: "Ezequiel 8"},
{id: "Ezequiel 9"},
{id: "Ezequiel 10"},
{id: "Ezequiel 11"},
{id: "Ezequiel 12"},
{id: "Ezequiel 13"},
{id: "Ezequiel 14"},
{id: "Ezequiel 15"},
{id: "Ezequiel 16"},
{id: "Ezequiel 17"},
{id: "Ezequiel 18"},
{id: "Ezequiel 19"},
{id: "Ezequiel 20"},
{id: "Ezequiel 21"},
{id: "Ezequiel 22"},
{id: "Ezequiel 23"},
{id: "Ezequiel 24"},
{id: "Ezequiel 25"},
{id: "Ezequiel 26"},
{id: "Ezequiel 27"},
{id: "Ezequiel 28"},
{id: "Ezequiel 29"},
{id: "Ezequiel 30"},
{id: "Ezequiel 31"},
{id: "Ezequiel 32"},
{id: "Ezequiel 33"},
{id: "Ezequiel 34"},
{id: "Ezequiel 35"},
{id: "Ezequiel 36"},
{id: "Ezequiel 37"},
{id: "Ezequiel 38"},
{id: "Ezequiel 39"},
{id: "Ezequiel 40"},
{id: "Ezequiel 41"},
{id: "Ezequiel 42"},
{id: "Ezequiel 43"},
{id: "Ezequiel 44"},
{id: "Ezequiel 45"},
{id: "Ezequiel 46"},
{id: "Ezequiel 47"},
{id: "Ezequiel 48"},
{id: "Daniel 1"},
{id: "Daniel 2"},
{id: "Daniel 3"},
{id: "Daniel 4"},
{id: "Daniel 5"},
{id: "Daniel 6"},
{id: "Daniel 7"},
{id: "Daniel 8"},
{id: "Daniel 9"},
{id: "Daniel 10"},
{id: "Daniel 11"},
{id: "Daniel 12"},
{id: "Oseas 1"},
{id: "Oseas 2"},
{id: "Oseas 3"},
{id: "Oseas 4"},
{id: "Oseas 5"},
{id: "Oseas 6"},
{id: "Oseas 7"},
{id: "Oseas 8"},
{id: "Oseas 9"},
{id: "Oseas 10"},
{id: "Oseas 11"},
{id: "Oseas 12"},
{id: "Oseas 13"},
{id: "Oseas 14"},
{id: "Joel 1"},
{id: "Joel 2"},
{id: "Joel 3"},
{id: "Amós 1"},
{id: "Amós 2"},
{id: "Amós 3"},
{id: "Amós 4"},
{id: "Amós 5"},
{id: "Amós 6"},
{id: "Amós 7"},
{id: "Amós 8"},
{id: "Amós 9"},
{id: "Abdías 1"},
{id: "Jonás 1"},
{id: "Jonás 2"},
{id: "Jonás 3"},
{id: "Jonás 4"},
{id: "Miqueas 1"},
{id: "Miqueas 2"},
{id: "Miqueas 3"},
{id: "Miqueas 4"},
{id: "Miqueas 5"},
{id: "Miqueas 6"},
{id: "Miqueas 7"},
{id: "Nahúm 1"},
{id: "Nahúm 2"},
{id: "Nahúm 3"},
{id: "Habacuc 1"},
{id: "Habacuc 2"},
{id: "Habacuc 3"},
{id: "Sofonías 1"},
{id: "Sofonías 2"},
{id: "Sofonías 3"},
{id: "Hageo 1"},
{id: "Hageo 2"},
{id: "Zacarías 1"},
{id: "Zacarías 2"},
{id: "Zacarías 3"},
{id: "Zacarías 4"},
{id: "Zacarías 5"},
{id: "Zacarías 6"},
{id: "Zacarías 7"},
{id: "Zacarías 8"},
{id: "Zacarías 9"},
{id: "Zacarías 10"},
{id: "Zacarías 11"},
{id: "Zacarías 12"},
{id: "Zacarías 13"},
{id: "Zacarías 14"},
{id: "Malaquías 1"},
{id: "Malaquías 2"},
{id: "Malaquías 3"},
{id: "Malaquías 4"},
{id: "Mateo 1"},
{id: "Mateo 2"},
{id: "Mateo 3"},
{id: "Mateo 4"},
{id: "Mateo 5"},
{id: "Mateo 6"},
{id: "Mateo 7"},
{id: "Mateo 8"},
{id: "Mateo 9"},
{id: "Mateo 10"},
{id: "Mateo 11"},
{id: "Mateo 12"},
{id: "Mateo 13"},
{id: "Mateo 14"},
{id: "Mateo 15"},
{id: "Mateo 16"},
{id: "Mateo 17"},
{id: "Mateo 18"},
{id: "Mateo 19"},
{id: "Mateo 20"},
{id: "Mateo 21"},
{id: "Mateo 22"},
{id: "Mateo 23"},
{id: "Mateo 24"},
{id: "Mateo 25"},
{id: "Mateo 26"},
{id: "Mateo 27"},
{id: "Mateo 28"},
{id: "Marcos 1"},
{id: "Marcos 2"},
{id: "Marcos 3"},
{id: "Marcos 4"},
{id: "Marcos 5"},
{id: "Marcos 6"},
{id: "Marcos 7"},
{id: "Marcos 8"},
{id: "Marcos 9"},
{id: "Marcos 10"},
{id: "Marcos 11"},
{id: "Marcos 12"},
{id: "Marcos 13"},
{id: "Marcos 14"},
{id: "Marcos 15"},
{id: "Marcos 16"},
{id: "Lucas 1"},
{id: "Lucas 2"},
{id: "Lucas 3"},
{id: "Lucas 4"},
{id: "Lucas 5"},
{id: "Lucas 6"},
{id: "Lucas 7"},
{id: "Lucas 8"},
{id: "Lucas 9"},
{id: "Lucas 10"},
{id: "Lucas 11"},
{id: "Lucas 12"},
{id: "Lucas 13"},
{id: "Lucas 14"},
{id: "Lucas 15"},
{id: "Lucas 16"},
{id: "Lucas 17"},
{id: "Lucas 18"},
{id: "Lucas 19"},
{id: "Lucas 20"},
{id: "Lucas 21"},
{id: "Lucas 22"},
{id: "Lucas 23"},
{id: "Lucas 24"},
{id: "Juan 1"},
{id: "Juan 2"},
{id: "Juan 3"},
{id: "Juan 4"},
{id: "Juan 5"},
{id: "Juan 6"},
{id: "Juan 7"},
{id: "Juan 8"},
{id: "Juan 9"},
{id: "Juan 10"},
{id: "Juan 11"},
{id: "Juan 12"},
{id: "Juan 13"},
{id: "Juan 14"},
{id: "Juan 15"},
{id: "Juan 16"},
{id: "Juan 17"},
{id: "Juan 18"},
{id: "Juan 19"},
{id: "Juan 20"},
{id: "Juan 21"},
{id: "Hechos 1"},
{id: "Hechos 2"},
{id: "Hechos 3"},
{id: "Hechos 4"},
{id: "Hechos 5"},
{id: "Hechos 6"},
{id: "Hechos 7"},
{id: "Hechos 8"},
{id: "Hechos 9"},
{id: "Hechos 10"},
{id: "Hechos 11"},
{id: "Hechos 12"},
{id: "Hechos 13"},
{id: "Hechos 14"},
{id: "Hechos 15"},
{id: "Hechos 16"},
{id: "Hechos 17"},
{id: "Hechos 18"},
{id: "Hechos 19"},
{id: "Hechos 20"},
{id: "Hechos 21"},
{id: "Hechos 22"},
{id: "Hechos 23"},
{id: "Hechos 24"},
{id: "Hechos 25"},
{id: "Hechos 26"},
{id: "Hechos 27"},
{id: "Hechos 28"},
{id: "Romanos 1"},
{id: "Romanos 2"},
{id: "Romanos 3"},
{id: "Romanos 4"},
{id: "Romanos 5"},
{id: "Romanos 6"},
{id: "Romanos 7"},
{id: "Romanos 8"},
{id: "Romanos 9"},
{id: "Romanos 10"},
{id: "Romanos 11"},
{id: "Romanos 12"},
{id: "Romanos 13"},
{id: "Romanos 14"},
{id: "Romanos 15"},
{id: "Romanos 16"},
{id: "1 Corintios 1"},
{id: "1 Corintios 2"},
{id: "1 Corintios 3"},
{id: "1 Corintios 4"},
{id: "1 Corintios 5"},
{id: "1 Corintios 6"},
{id: "1 Corintios 7"},
{id: "1 Corintios 8"},
{id: "1 Corintios 9"},
{id: "1 Corintios 10"},
{id: "1 Corintios 11"},
{id: "1 Corintios 12"},
{id: "1 Corintios 13"},
{id: "1 Corintios 14"},
{id: "1 Corintios 15"},
{id: "1 Corintios 16"},
{id: "2 Corintios 1"},
{id: "2 Corintios 2"},
{id: "2 Corintios 3"},
{id: "2 Corintios 4"},
{id: "2 Corintios 5"},
{id: "2 Corintios 6"},
{id: "2 Corintios 7"},
{id: "2 Corintios 8"},
{id: "2 Corintios 9"},
{id: "2 Corintios 10"},
{id: "2 Corintios 11"},
{id: "2 Corintios 12"},
{id: "2 Corintios 13"},
{id: "Gálatas 1"},
{id: "Gálatas 2"},
{id: "Gálatas 3"},
{id: "Gálatas 4"},
{id: "Gálatas 5"},
{id: "Gálatas 6"},
{id: "Efesios 1"},
{id: "Efesios 2"},
{id: "Efesios 3"},
{id: "Efesios 4"},
{id: "Efesios 5"},
{id: "Efesios 6"},
{id: "Filipenses 1"},
{id: "Filipenses 2"},
{id: "Filipenses 3"},
{id: "Filipenses 4"},
{id: "Colosenses 1"},
{id: "Colosenses 2"},
{id: "Colosenses 3"},
{id: "Colosenses 4"},
{id: "1 Tesalonicenses 1"},
{id: "1 Tesalonicenses 2"},
{id: "1 Tesalonicenses 3"},
{id: "1 Tesalonicenses 4"},
{id: "1 Tesalonicenses 5"},
{id: "2 Tesalonicenses 1"},
{id: "2 Tesalonicenses 2"},
{id: "2 Tesalonicenses 3"},
{id: "1 Timoteo 1"},
{id: "1 Timoteo 2"},
{id: "1 Timoteo 3"},
{id: "1 Timoteo 4"},
{id: "1 Timoteo 5"},
{id: "1 Timoteo 6"},
{id: "2 Timoteo 1"},
{id: "2 Timoteo 2"},
{id: "2 Timoteo 3"},
{id: "2 Timoteo 4"},
{id: "Tito 1"},
{id: "Tito 2"},
{id: "Tito 3"},
{id: "Filemón 1"},
{id: "Hebreos 1"},
{id: "Hebreos 2"},
{id: "Hebreos 3"},
{id: "Hebreos 4"},
{id: "Hebreos 5"},
{id: "Hebreos 6"},
{id: "Hebreos 7"},
{id: "Hebreos 8"},
{id: "Hebreos 9"},
{id: "Hebreos 10"},
{id: "Hebreos 11"},
{id: "Hebreos 12"},
{id: "Hebreos 13"},
{id: "Santiago 1"},
{id: "Santiago 2"},
{id: "Santiago 3"},
{id: "Santiago 4"},
{id: "Santiago 5"},
{id: "1 Pedro 1"},
{id: "1 Pedro 2"},
{id: "1 Pedro 3"},
{id: "1 Pedro 4"},
{id: "1 Pedro 5"},
{id: "2 Pedro 1"},
{id: "2 Pedro 2"},
{id: "2 Pedro 3"},
{id: "1 Juan 1"},
{id: "1 Juan 2"},
{id: "1 Juan 3"},
{id: "1 Juan 4"},
{id: "1 Juan 5"},
{id: "2 Juan 1"},
{id: "3 Juan 1"},
{id: "Judas 1"},
{id: "Apocalipsis 1"},
{id: "Apocalipsis 2"},
{id: "Apocalipsis 3"},
{id: "Apocalipsis 4"},
{id: "Apocalipsis 5"},
{id: "Apocalipsis 6"},
{id: "Apocalipsis 7"},
{id: "Apocalipsis 8"},
{id: "Apocalipsis 9"},
{id: "Apocalipsis 10"},
{id: "Apocalipsis 11"},
{id: "Apocalipsis 12"},
{id: "Apocalipsis 13"},
{id: "Apocalipsis 14"},
{id: "Apocalipsis 15"},
{id: "Apocalipsis 16"},
{id: "Apocalipsis 17"},
{id: "Apocalipsis 18"},
{id: "Apocalipsis 19"},
{id: "Apocalipsis 20"},
{id: "Apocalipsis 21"},
{id: "Apocalipsis 22"}
  ];

  const links = [
    {source: "Genesis 1", target: "Genesis 2"},
    {source: "Matthew 5", target: "Exodus 12"},
    {source: "Matthew 27", target: "John 20"},
    {source: "Genesis 1", target: "John 20"}
  ];

  const color = d3.scaleOrdinal(d3.schemeCategory10);

  // limpiar svg previo
  d3.select("#viz").selectAll("svg").remove();

  const svg = d3.select("#viz")
    .append("svg")
    .attr("width", width)
    .attr("height", height);

  const g = svg.append("g")
    .attr("transform", `translate(${margin.left},${margin.top})`);

  // escala horizontal
  const x = d3.scalePoint()
    .domain(nodes.map(d => d.id))
    .range([0, innerWidth])
    .padding(0.5);

  // línea base ubicada en la parte inferior del área interna
  const baselineY = innerHeight;

  // asignar coords
  nodes.forEach(d => {
    d.x = x(d.id);
    d.y = baselineY;
  });

  // arcos
  g.selectAll("path.link")
    .data(links)
    .join("path")
    .attr("fill", "none")
    .attr("stroke", d => color(d.source))
    .attr("stroke-width", 1.5)
    .attr("d", d => {
      const s = nodes.find(n => n.id === d.source);
      const t = nodes.find(n => n.id === d.target);
      const x1 = s.x, x2 = t.x;
      const y = baselineY;
      const r = Math.abs(x2 - x1) / 2; // radio
      const sweep = x1 < x2 ? 1 : 0;
      return `M${x1},${y} A${r},${r} 0 0,${sweep} ${x2},${y}`;
    })
    .attr("opacity", 0.7);

  // nodos
  g.selectAll("circle.node")
    .data(nodes)
    .join("circle")
    .attr("r", 5)
    .attr("cx", d => d.x)
    .attr("cy", d => d.y)
    .attr("fill", d => color(d.id));

  // Etiquetas
  g.selectAll("text.label")
    .data(nodes)
    .join("text")
    .attr("class", "label")
    .attr("x", d => d.x)
    .attr("y", d => d.y + 20)   // colocar el punto base justo encima del nodo
    .attr("text-anchor", "end") // el texto termina en el punto dado
    .attr("font-size", 11)
    .attr("transform", d => `rotate(-90, ${d.x}, ${d.y + 20})`)
    .text(d => d.id);

}


document.getElementById('btn-expand').addEventListener('click', expandAll);
document.getElementById('btn-collapse').addEventListener('click', collapseAll);

// Expose data for debugging/edit desde consola
window._BC_DATA = data;

// llamar al render del gráfico
document.addEventListener("DOMContentLoaded", () => {
  drawViz();
});

